CREATE TABLE IF NOT EXISTS public."user" (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                           name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );
CREATE TABLE IF NOT EXISTS item (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    name VARCHAR(255) NOT NULL,
    description VARCHAR(512) NOT NULL,
    available BOOLEAN NOT NULL,
    owner_id BIGINT NOT NULL,
    request VARCHAR(255) ,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT FK_USER_ID FOREIGN KEY(owner_id) REFERENCES public."user"(id)
    );
